version: '3.8'

services:

  server:
    image: miloszaw/pgfs:server
    #build:
    #  context: ./
    #  dockerfile: ./server/Dockerfile
    expose:
      - "80"
    ports:
      - "5100:80"

  sender:
    image: miloszaw/pgfs:sender
    #build:
    #  context: ./
    #  dockerfile: sender/Dockerfile
    expose:
      - "81"
    ports:
      - "5101:81"
    depends_on:
      - server

  reciever:
    image: miloszaw/pgfs:reciever
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    expose:
      - "82"
    ports:
      - "5102:82"
    depends_on:
      - sender